BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS `tbl_Buecher` (
	`ID`	INTEGER NOT NULL UNIQUE,
	`Name`	TEXT NOT NULL UNIQUE,
	`Author`	INTEGER NOT NULL UNIQUE,
	`Erscheinungsjahr`	INTEGER NOT NULL UNIQUE,
	PRIMARY KEY(`ID`)
);
CREATE TABLE IF NOT EXISTS `tbl_Autor` (
	`ID`	INTEGER NOT NULL UNIQUE,
	`Name`	TEXT NOT NULL UNIQUE,
	PRIMARY KEY(`ID`)
);
COMMIT;
